WPF support for ARM64: WPF ARM64 public repo Packaging updates
dotnet/wpf pull request #4048
Opened 2021-01-21 06:44 UTC by ryalanms

Packaging updates should be turned on when ARM64 builds are enabled in the pipeline.  

Co-authored-by: Alexandre Zollinger Chohfi <...>
Co-authored-by: Marcpems <...>
Co-authored-by: Juan Sebastian Hoyos Ayala <...>
Co-authored-by: Ryland <41491307+ryalanms@users.noreply.github.com>

/cc @azchohfi @hoyosjs @marcpems

2021-01-21 06:47 UTC, hoyosjs commented
Any reason not to include the packaging + pipeline changes here?

2021-01-21 06:54 UTC, ryalanms commented
We could combine them, I suppose.

2021-01-21 12:19 UTC, hoyosjs approved these changes

2021-01-21 12:19 UTC, hoyosjs commented on NuGet.config
> -    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
This looks like an unintentional change.

2021-01-21 18:09 UTC, ryalanms commented
This PR build will not pass until the other dependent PRs are merged.

2021-01-21 18:35 UTC, azchohfi requested changes
Only the nuget.config change seems wrong.

2021-01-21 21:45 UTC, azchohfi approved these changes

2021-01-22 03:53 UTC, ryalanms commented
/azp run

2021-01-22 04:11 UTC, ryalanms commented
There are failures in our APICompat checks.  Investigating...

2021-01-22 05:04 UTC, merged