Add WPF .vsconfig to release/3.1 (contains 4.6.2 required for module initializer injection)
dotnet/wpf pull request #5402
Opened 2021-09-28 22:32 UTC by ryalanms

This was missing from release/3.1.  .NET Framework 4.6.2 is required to build locally.

2021-09-28 23:49 UTC, SamBent requested changes
If you don't have 4.6.2.SDK installed, the build fails with this message:
```
D:\repos\wpf\eng\WpfArcadeSdk\tools\InjectModuleInitializer.targets(372,5): error MSB4044: The "ILDasmTask" task was not given a value for the required parameter "ILDAsm". [D:\repos\wpf\src\Microsoft.DotNet.Wpf\src\PresentationCore\PresentationCore.csproj]
```

Do your changes affect that?  I doubt it - the build doesn't depend on files in the Documentation folder, does it?

Please mention the message and the remedy (install 4.6.2.SDK) here.  I don't expect anyone can figure it out on their own.

Also, why is 4.7.2.TargetingPack needed?

2021-10-18 08:29 UTC, vishalmsft commented on Documentation/wpf.vsconfig
> +    "Microsoft.VisualStudio.Component.Windows10SDK.18362"
Need WindowsSDK.17134. Missing SDK is causing DirectWriteForwarder.vcxproj to fail.
Adding the line "Microsoft.VisualStudio.Component.Windows10SDK.17134" gets WPF compiling.

2022-03-09 00:14 UTC, RussKie commented
3.1 is nearing its EOL. Is there a compelling reason to service it? If not - suggest closing this PR.

2022-03-11 16:00 UTC, dipeshmsft commented
Closing this PR as per the reason mentioned above.

2022-03-11 16:00 UTC, closed without merging