Update tooltip.md
dotnet/wpf pull request #5668
Opened 2021-11-09 12:31 UTC by gurpreet-wpf

https://github.com/dotnet/wpf/issues/5132
Updating tooltip specs (CTRL and ESP will close any tooltip) as per the latest requirements from Accessibility team.

Fixes Issue 

Main PR 

## Description

https://github.com/dotnet/wpf/issues/5132
Updated tooltip specs accordingly

## Customer Impact

## Regression

## Testing

## Risk

2021-11-09 22:36 UTC, SamBent requested changes

2021-11-09 22:36 UTC, SamBent commented on src/Microsoft.DotNet.Wpf/specs/tooltip.md
> +- **Keyboard Shortcut**. Typing Ctrl+Shift+F10 or simply Ctrl closes any open tooltip whether it is opened from keyboard or mouse. Typing ESC closes any open tooltip.
#5132 quotes the accessibility working group:  "Esc may have consequences beyond the tooltip, and the user would be taking that responsibility on if they do not choose to use Ctrl."  That quote should appear in the spec somewhere.  This bullet might be the best place?

2021-11-24 12:00 UTC, gurpreet-wpf commented
@SamBent I have implemented the changes suggested by you. Could you please review?

2021-11-30 00:28 UTC, SamBent approved these changes

2021-12-01 05:20 UTC, merged