Fix NullReferenceException in Invariant.get_IsDialogOverrideEnabled
dotnet/wpf pull request #6785
Opened 2022-07-12 19:30 UTC by VladimirKhil

Fixes # 6772

## Description

Fix NullReferenceException in Invariant.get_IsDialogOverrideEnabled when .NET Framework Registry key (HKLM\Software\Microsoft\.NETFramework) is not present on the machine

## Customer Impact

-

## Regression

-

## Testing

-

## Risk

-

2022-07-28 23:03 UTC, miloush commented
Is there a reason for splitting the declaration from assignment?

2022-08-31 06:14 UTC, dipeshmsft commented
> Is there a reason for splitting the declaration from assignment?

Can't think of a reason, I guess we should merge the declaration and assignment for both the variables.

2022-08-31 06:48 UTC, dipeshmsft commented on src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Invariant.cs
> +                    dbgManagedDebuggerValue = key.GetValue("DbgManagedDebugger") as string;
```suggestion
                    object dbgJITDebugLaunchSettingValue = key.GetValue("DbgJITDebugLaunchSetting");
                    string dbgManagedDebuggerValue = key.GetValue("DbgManagedDebugger") as string;
```

2022-08-31 06:51 UTC, dipeshmsft commented on src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Invariant.cs
> +                    dbgManagedDebuggerValue = key.GetValue("DbgManagedDebugger") as string;
Can you merge the declaration here and remove the declarations from Line 241-242

2022-08-31 18:42 UTC, dipeshmsft requested changes
Can you merge the declaration here and remove the declarations from Line 241-242

2022-09-03 16:21 UTC, VladimirKhil commented
> Can you merge the declaration here and remove the declarations from Line 241-242

Done.

2022-09-03 16:26 UTC, dipeshmsft commented on src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Invariant.cs
>                  object dbgJITDebugLaunchSettingValue;
We can remove the declaration from here

2022-09-10 05:46 UTC, VladimirKhil commented on src/Microsoft.DotNet.Wpf/src/Shared/MS/Internal/Invariant.cs
>                  object dbgJITDebugLaunchSettingValue;
Done.

2022-09-10 06:40 UTC, dipeshmsft approved these changes

2022-09-10 06:41 UTC, dipeshmsft commented
/azp run

2022-09-16 05:33 UTC, pchaurasia14 commented
/azp run

2022-09-22 06:48 UTC, pchaurasia14 commented
/azp run

2022-10-26 02:43 UTC, merged

2022-10-26 02:49 UTC, dipeshmsft commented
Thanks for the contribution @VladimirKhil