Update TFM from .net7.0 to .net8.0
dotnet/wpf pull request #7219
Opened 2022-10-20 08:28 UTC by rchauhan18

Update TFM from .net7.0 to .net8.0

2022-10-23 23:08 UTC, RussKie approved these changes

2022-10-23 23:09 UTC, RussKie commented
```
D:\a\_work\1\s\.dotnet\sdk\8.0.100-alpha.1.22512.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1005: Assets file 'D:\a\_work\1\s\artifacts\obj\PresentationBuildTasks\project.assets.json' doesn't have a target for 'net8.0'. Ensure that restore has run and that you have included 'net8.0' in the TargetFrameworks for your project. [D:\a\_work\1\s\src\Microsoft.DotNet.Wpf\src\PresentationBuildTasks\PresentationBuildTasks.csproj::TargetFramework=net8.0]
##[error].dotnet\sdk\8.0.100-alpha.1.22512.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1005: (NETCORE_ENGINEERING_TELEMETRY=Build) Assets file 'D:\a\_work\1\s\artifacts\obj\PresentationBuildTasks\project.assets.json' doesn't have a target for 'net8.0'. Ensure that restore has run and that you have included 'net8.0' in the TargetFrameworks for your project.
```

2022-10-25 04:17 UTC, dipeshmsft commented
@rchauhan18 , you will need to update TFM to net8.0 in PresentationBuildTasks.csproj.

2022-10-25 04:19 UTC, dipeshmsft requested changes
You will have to change TFM to net8.0 in PresentationBuildTasks.csproj

https://github.com/dotnet/wpf/blob/89620aa2bd732a2072d9d38601be1587a4d73572/src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/PresentationBuildTasks.csproj#L2-L4

2022-10-25 10:47 UTC, dipeshmsft approved these changes

2022-10-25 10:49 UTC, merged